//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSTEntities : DbContext
    {
        public TSTEntities()
            : base("name=TSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TSTChatroom> TSTChatrooms { get; set; }
        public virtual DbSet<TSTCourseDepartment> TSTCourseDepartments { get; set; }
        public virtual DbSet<TSTCourseInstance> TSTCourseInstances { get; set; }
        public virtual DbSet<TSTCours> TSTCourses { get; set; }
        public virtual DbSet<TSTCourseStatus> TSTCourseStatuses { get; set; }
        public virtual DbSet<TSTDepartment> TSTDepartments { get; set; }
        public virtual DbSet<TSTEmployee> TSTEmployees { get; set; }
        public virtual DbSet<TSTEmployeeStatus> TSTEmployeeStatuses { get; set; }
        public virtual DbSet<TSTMessage> TSTMessages { get; set; }
        public virtual DbSet<TSTPriorite> TSTPriorites { get; set; }
        public virtual DbSet<TSTTechNote> TSTTechNotes { get; set; }
        public virtual DbSet<TSTTicket> TSTTickets { get; set; }
        public virtual DbSet<TSTTicketStatus> TSTTicketStatuses { get; set; }
        public virtual DbSet<TSTStudents_Courses> TSTStudents_Courses { get; set; }
    }
}
