//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTEmployee()
        {
            this.TSTCourseInstances = new HashSet<TSTCourseInstance>();
            this.TSTMessages = new HashSet<TSTMessage>();
            this.TSTStudents_Courses = new HashSet<TSTStudents_Courses>();
            this.TSTTechNotes = new HashSet<TSTTechNote>();
            this.TSTTickets = new HashSet<TSTTicket>();
            this.TSTTickets1 = new HashSet<TSTTicket>();
            this.TSTChatrooms = new HashSet<TSTChatroom>();
        }
    
        public int EmpID { get; set; }
        public string EmpFname { get; set; }
        public string EmpLname { get; set; }
        public int DepartmentID { get; set; }
        public int EmpStatusID { get; set; }
        public string EmpAddress1 { get; set; }
        public string EmpAddress2 { get; set; }
        public string EmpCity { get; set; }
        public string EmpState { get; set; }
        public string EmpPhoto { get; set; }
        public string EmpUserID { get; set; }
        public System.DateTime EmpDateOfBirth { get; set; }
        public System.DateTime EmpDateOfHire { get; set; }
        public Nullable<System.DateTime> EmpEndDate { get; set; }
        public string EmpPhone { get; set; }
        public string EmpEmail { get; set; }
        public string EmpNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTCourseInstance> TSTCourseInstances { get; set; }
        public virtual TSTDepartment TSTDepartment { get; set; }
        public virtual TSTEmployeeStatus TSTEmployeeStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTMessage> TSTMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTStudents_Courses> TSTStudents_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTechNote> TSTTechNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicket> TSTTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicket> TSTTickets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTChatroom> TSTChatrooms { get; set; }
    }
}
