//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTMessage()
        {
            this.TSTChatrooms = new HashSet<TSTChatroom>();
        }
    
        public int MessageID { get; set; }
        public int SenderID { get; set; }
        public string Message { get; set; }
        public System.DateTime TimeSent { get; set; }
        public Nullable<bool> HasBeenSeen { get; set; }
    
        public virtual TSTEmployee TSTEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTChatroom> TSTChatrooms { get; set; }
    }
}
