//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTStudents_Courses
    {
        public int StudentID { get; set; }
        public int CourseInstanceID { get; set; }
        public Nullable<double> StudentGrade { get; set; }
        public Nullable<bool> StudentPassed { get; set; }
    
        public virtual TSTCourseInstance TSTCourseInstance { get; set; }
        public virtual TSTEmployee TSTEmployee { get; set; }
    }
}
