//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTTicket()
        {
            this.TSTTechNotes = new HashSet<TSTTechNote>();
        }
    
        public int TicketID { get; set; }
        public string TicketSubject { get; set; }
        public string TicketDescription { get; set; }
        public int SubmittedByID { get; set; }
        public Nullable<int> TechID { get; set; }
        public System.DateTime TicketSubmitted { get; set; }
        public Nullable<System.DateTime> TicketResolved { get; set; }
        public int TicketStatusID { get; set; }
        public string Image { get; set; }
        public int PriorityID { get; set; }
    
        public virtual TSTEmployee TSTEmployee { get; set; }
        public virtual TSTEmployee TSTEmployee1 { get; set; }
        public virtual TSTPriorite TSTPriorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTechNote> TSTTechNotes { get; set; }
        public virtual TSTTicketStatus TSTTicketStatus { get; set; }
    }
}
